# Generated by Django 3.2.4 on 2021-06-04 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Couriers',
            fields=[
                ('courier_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('courier_type', models.CharField(choices=[('foot', 'foot'), ('bike', 'bike'), ('car', 'car')], max_length=255)),
                ('regions', models.CharField(max_length=255)),
                ('working_hours', models.CharField(max_length=255)),
                ('assign_time_current_for_delivery', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('weight', models.FloatField()),
                ('region', models.IntegerField()),
                ('delivery_hours', models.CharField(max_length=255)),
                ('complete', models.BooleanField(default=False)),
                ('complete_time', models.DateTimeField(null=True)),
                ('assign_time', models.DateTimeField(null=True)),
                ('courier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.couriers')),
            ],
        ),
    ]
