# Generated by Django 3.2.4 on 2021-06-04 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('gender', models.CharField(blank=True, choices=[('definite', (('w', 'woman'), ('m', 'man'))), ('indefinite', (('t', 'trans'), ('o', 'other')))], max_length=100, null=True, verbose_name='Пол')),
                ('email', models.CharField(default='', max_length=255, verbose_name='email')),
                ('phone', models.CharField(blank=True, default='', max_length=255, verbose_name='телефон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
