# Generated by Django 3.2.4 on 2021-06-04 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='courier',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.couriers', verbose_name='Курьер'),
            preserve_default=False,
        ),
    ]
